version: '3.7'
services:
  web:
    build:
      context: ${SERVER_ROOT}/bin/${PHP_VERSION}
    container_name: web
    restart: 'always'
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80
      - ${HOST_MACHINE_SECURE_HOST_PORT}:443
    environment:
      - ENV=dev
    volumes:
      # development directory
      - ${PROJECT_ROOT}:/var/www/html/
      - ${SERVER_ROOT}${PHP_DATA_DIR}:/docker/etc/php7/
      - ${SERVER_ROOT}${APACHE_DATA_DIR}:/docker/etc/apache2/
      - ${SERVER_ROOT}${APACHE_LOG_DIR}:/var/log/apache2/
