version: '3.7'
services:
  web:
    build:
      context: ${SERVER_ROOT}/bin/${PHP_VERSION}
    container_name: web
    restart: 'always'
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80
      - ${HOST_MACHINE_SECURE_HOST_PORT}:443
    environment:
      - ENV=dev
    volumes:
      # development directory
      - ${PROJECT_ROOT}:/var/www/html/
      - ${SERVER_ROOT}${PHP_DATA_DIR}:/docker/etc/php7/
      - ${SERVER_ROOT}${APACHE_DATA_DIR}:/docker/etc/apache2/
      - ${SERVER_ROOT}${APACHE_LOG_DIR}:/var/log/apache2/
  # database:
  #   build:
  #     context: "${SERVER_ROOT}/bin/${MYSQL_VERSION}"
  #   container_name: ${MYSQL_VERSION}
  #   restart: 'always'
  #   ports:
  #     - "${HOST_MACHINE_MYSQL_PORT}:3306"
  #   volumes:
  #     - ${SERVER_ROOT}${MYSQL_DATA_DIR}:/var/lib/mysql
  #     - ${SERVER_ROOT}${MYSQL_LOG_DIR}:/var/log/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: 'phpmyadmin'
  #   links:
  #     - database
  #   ports:
  #     - "${HOST_MACHINE_PHPMYADMIN_PORT}:80"
  #   volumes:
  #     - /sessions
  #     - ${SERVER_ROOT}${PHP_DATA_DIR}:/docker/etc/php7/conf.d/php-phpmyadmin.ini
  #   environment:
  #     PMA_HOST: database
  #     PMA_PORT: ${HOST_MACHINE_MYSQL_PORT}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     PMA_USER: ${MYSQL_USER}
  #     PMA_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}